# Generated by Django 4.2.3 on 2023-08-28 01:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_card_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='US DOLLAR', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
                ('receivers_name', models.CharField(max_length=50)),
                ('beneficiary_account_number', models.CharField(max_length=20)),
                ('beneficiary_bank_address', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('dotf', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_success', models.CharField(choices=[('success', 'SUCCESS'), ('pending', 'PENDING'), ('failed', 'FAILED')], default='pending')),
                ('reference', models.CharField(max_length=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_transfer', to='clients.savings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_transfer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
