# Generated by Django 4.2.3 on 2023-08-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_customuser_managers_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
