# Generated by Django 4.2.3 on 2023-08-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_savings_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
