# Generated by Django 4.2.3 on 2023-08-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_savings_tiers_alter_transfer_user_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_success',
            field=models.CharField(choices=[('success', 'SUCCESS'), ('pending', 'PENDING'), ('failed', 'FAILED')], default='pending'),
        ),
    ]
