# Generated by Django 4.2.3 on 2023-09-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='E45731A02AF', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'SUCCESS'), ('pending', 'PENDING'), ('failed', 'FAILED')], default='success'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='reference',
            field=models.CharField(default='563B395DDFA', max_length=15),
        ),
    ]
