# Generated by Django 4.2.3 on 2023-11-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_card_user_alter_transaction_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardrequest',
            old_name='created',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='B4C1009327A', max_length=15),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='reference',
            field=models.CharField(default='9EC00C2DC1E', max_length=15),
        ),
    ]
