# Generated by Django 4.2.3 on 2023-11-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_alter_transaction_reference_alter_transfer_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='32F68E581D5', max_length=15),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='reference',
            field=models.CharField(default='129D8B9A9BC', max_length=15),
        ),
        migrations.DeleteModel(
            name='CardRequest',
        ),
    ]
